last_modified = "2021-08-17"

open_source = [
  "https://github.com/exercism/dart",
  "https://github.com/nushell/book",
  "https://github.com/rust-lang/book",
  "https://github.com/rust-lang/rust-by-example",
]

summary = [
  "Six years of Web development experience.",
  "Three years of full-stack experience, including Python, Java, Node.js, React and SQL.",
  "Experience working solo and with teams in start-ups and medium-sized enterprises.",
  "Five years of Agile software development.",
]

[[education]]
end_date = "2015"
institution = "Queen Mary University of London"
title = "MSc Software Engineering"

[[education]]
end_date = "2013"
institution = "Faculty of Sciences, University of Lisbon"
title = "BEng Computer Science"

[[education]]
end_date = "2010"
institution = "NHK (Lisbon, Portugal)"
title = "Java Course"

[[skills]]
category = "Databases"
values = [
  "MongoDB",
  "MySQL",
  "PostgreSQL",
]

[[skills]]
category = "Programming languages"
values = [
  "C",
  "Dart",
  "Haskell",
  "Java",
  "JavaScript",
  "PHP",
  "Python",
  "Rust",
  "TypeScript",
]

[[skills]]
category = "Tools"
values = [
  "AWS",
  "Git",
  "Google Cloud",
  "Linux",
  "macOS",
  "UNIX",
  "Vim/Neovim",
]

[[skills]]
category = "Web"
values = [
  "AngularJS",
  "CSS",
  "Cypress",
  "Django",
  "Doctrine",
  "Ember.js",
  "Express",
  "Flask",
  "HTML",
  "Jasmine",
  "Jest",
  "Node.js",
  "Nuxt.js",
  "React",
  "Redux",
  "Vue.js",
  "WebdriverIO",
]

[[work_experience]]
description = [
  "Created and maintained content management tools in Express and Nuxt.js using TypeScript.",
  "Built a back-end service in Express using TypeScript and a MongoDB database to provide environment configurations to tools and game clients.",
  "Wrote unit tests in Jest and Jasmine.",
  "Maintained customer support platforms built in Java.",
  "Configured Google Cloud to automate the deployment of services and applications.",
]
from_date = "2020"
location = "London, UK"
organisation = "Supersolid"
title = "Server Developer"
to_date = "present"
website = "https://supersolid.com"

[[work_experience]]
description = [
  "Worked on the migration of parts of a Ruby on Rails monolithic application to several modular React & Redux applications.",
  "Contributed to a design system made of React components, which improved the design, user experience and accessibility of the React applications.",
  "Configured JSON tokens to enable business-to-business (B2B) customisations.",
  "Used visual regression tests to guarantee the visual correctness of all products.",
  "Wrote unit tests in Jest and Enzyme to maintain 100% line coverage of the entire codebase, as well as end-to-end tests in Cypress and WebdriverIO.",
  "Configured Jenkins pipelines to optimise the deployment process and to run tests automatically.",
]
from_date = "2018"
location = "London, UK"
organisation = "Nutmeg"
title = "Software Engineer"
to_date = "2020"
website = "https://www.nutmeg.com"

[[work_experience]]
description = [
  "Maintained and implemented new features for the AngularJS website and the private intranet in Ember.js.",
  "Created new stored procedures for the PostgreSQL database to support new API endpoints and improve its performance.",
  "Added new endpoints to the REST API using Express.",
  "Became the user interface/experience (UI/UX) lead within a year of my employment.",
  "Migrated the AngularJS website to React & Redux with server-side rendering.",
  "Developed widgets in React, which doctors and clinics could embed on their websites.",
]
from_date = "2016"
location = "London, UK"
organisation = "Doctify"
title = "Software Engineer"
to_date = "2018"
website = "https://www.doctify.com"

[[work_experience]]
description = [
  "Worked on a prototype in Laravel (PHP) with a MySQL database to build a business-to-business (B2B) platform.",
  "Designed and documented a new architecture for the API, with enhanced security and authentication methods.",
  "Provided technical support to the sales and finance teams.",
]
from_date = "2016"
location = "London, UK"
organisation = "Kapow SMS Communications"
title = "Web Developer"
to_date = "2016"
website = "https://www.kapow.co.uk"


[[work_experience]]
description = [
  "Worked solo on a Web-based database to manage clinical trials and associated resources. The platform was originally developed in Symfony and Doctrine (PHP), but later migrated to Django (Python) with a MySQL database.",
  "Created the website for my department using HTML, CSS and JavaScript.",
  "Developed and performed quality control of OpenClinica and REDCap databases.",
  "Deployed Apache and Tomcat Web servers hosting OpenClinica and REDCap databases.",
]
from_date = "2015"
location = "London, UK"
organisation = "PCTU, Queen Mary University of London"
title = "Software Developer"
to_date = "2016"
website = "https://www.qmul.ac.uk/pctu"
