[[entries]]
category = "Currently reading"

[[entries.books]]
author = "Elliot B. Koffman; Paul A. T. Wolfgang"
isbn = "9780471692645"
date_finished = "present"
date_started = "5 Oct 2020"
title = "Objects, Abstraction, Data Structures and Design Using Java Version 5.0"

[[entries.books]]
author = "J.K. Rowling"
isbn = "9781781106464"
date_finished = "present"
date_started = "29 Jun 2020"
title = "Harry Potter: The Complete Collection"

[[entries]]
category = "2020"

[[entries.books]]
author = "J.K. Rowling"
date_finished = "10 Jul"
date_started = "26 May"
title = "The Ickabog"

[[entries.books]]
author = "Marieke Eyskoot"
date_finished = "4 May"
date_started = "15 Nov 2019"
isbn = "9789063694920"
title = "This is a Good Guide - for a sustainable lifestyle"

[[entries]]
category = "2019"

[[entries.books]]
author = "Gene Kim; Kevin Behr; George Spafford"
date_finished = "27 Dec"
date_started = "25 Nov"
isbn = "9781942788300"
title = "The Phoenix Project: A Novel About IT, DevOps, and Helping Your Business Win"

[[entries.books]]
author = "Margaret Atwood"
date_finished = "12 Nov"
date_started = "16 Oct"
isbn = "9781784873189"
title = "The Handmaid's Tale"

[[entries.books]]
author = "Andy Lester"
date_finished = "15 Oct"
date_started = "25 Set"
isbn = "9781934356265"
title = "Land the Tech Job You Love"

[[entries.books]]
author = "Daniel Stenberg"
date_finished = "24 Sep"
date_started = "27 Aug"
isbn = "9789163965012"
title = "Everything curl"

[[entries.books]]
author = "Home Office"
date_finished = "26 Aug"
date_started = "31 Jul"
isbn = "9780113413409"
title = "Life in the United Kingdom: A Guide for New Residents"

[[entries.books]]
author = "Jason Fried; David Heinemeier Hansson"
date_finished = "8 Aug"
date_started = "29 Jul"
isbn = "9780008323455"
title = "It Doesn't Have to Be Crazy at Work"

[[entries.books]]
author = "Greg Jackson"
date_finished = "26 Jul"
date_started = "11 Jul"
isbn = "9781783782017"
title = "Prodigals: Stories"

[[entries.books]]
author = "Shoshana Zuboff"
date_finished = "11 Jul"
isbn = "9781782832744"
date_started = "23 Apr"
title = "The Age of Surveillance Capitalism: The Fight for a Human Future at the New Frontier of Power"

[[entries.books]]
author = "Edward Bellamy"
date_finished = "22 Apr"
date_started = "17 Mar"
title = "Looking Backward: 2000-1887"

[[entries.books]]
author = "Jim Blandy"
date_finished = "31 Mar"
date_started = "22 Mar"
isbn = "9781491927298"
title = "Why Rust?"

[[entries.books]]
author = "Joanna Cannon"
date_finished = "07 Mar"
date_started = "30 Nov 2018"
isbn = "9780008132187"
title = "The Trouble with Goats and Sheep"

[[entries.books]]
author = "Steve Klabnik; Carol Nichols"
date_finished = "25 Jan"
date_started = "11 Dec 2018"
title = "The Rust Programming Language"

[[entries]]
category = "2018"

[[entries.books]]
author = "V.C. Vickers"
date_finished = "8 Dec"
date_started = "8 Dec"
isbn = "9780192797353"
title = "The Google Book"

[[entries.books]]
author = "Tim Minchin"
date_finished = "1 Dec"
date_started = "1 Dec"
isbn = "9781409156253"
title = "Storm"

[[entries.books]]
author = "Sarah Winman"
date_finished = "29 Nov"
date_started = "1 Nov"
isbn = "9780755379316"
title = "When God Was a Rabbit"

[[entries.books]]
author = "Allen Ginsberg"
date_finished = "18 Nov"
isbn = "9780872863101"
date_started = "18 Nov"
title = "Howl and Other Poems"

[[entries.books]]
author = "Rebecca Solnit"
date_finished = "10 Nov"
date_started = "6 Sep"
isbn = "9780520262492"
title = "Infinite City: A San Francisco Atlas"

[[entries.books]]
author = "Caitlin Moran"
date_finished = "31 Oct"
date_started = "21 Aug"
isbn = "9781446406168"
title = "How To Be a Woman"

[[entries.books]]
author = "Sebastián Peyrott"
date_finished = "27 Aug"
date_started = "14 Aug"
title = "JWT Handbook"

[[entries.books]]
author = "Sheldon B. Kopp"
date_finished = "13 Aug"
date_started = "24 Jul"
isbn = "9780804150965"
title = "If You Meet the Buddha on the Road, Kill Him: The Pilgrimage of Psychotherapy Patients"

[[entries.books]]
author = "Rosalie Ham"
date_finished = "23 Jul"
date_started = "22 May"
isbn = "9781782830719"
title = "The Dressmaker"

[[entries.books]]
author = "Andrew Hunt; David Thomas"
date_finished = "18 Jun"
date_started = "7 Apr"
isbn = "9780201616224"
title = "The Pragmatic Programmer: From Journeyman to Master"

[[entries.books]]
author = "Julia Rochester"
date_finished = "7 Apr"
isbn = "9780241971703"
title = "The House at the Edge of the World"

[[entries]]
category = "2017"

[[entries.books]]
author = "Alan Hollinghurst"
date_finished = "27 Dec"
isbn = "9781409002260"
title = "The Swimming Pool Library"

[[entries.books]]
author = "Kevin Starr"
date_finished = "7 Sep"
isbn = "9780307430755"
title = "California: A History"

[[entries]]
category = "2016"

[[entries.books]]
author = "Sean Patrick"
date_finished = "30 Oct"
isbn = "9781938895173"
title = "Nikola Tesla: Imagination and the Man That Invented the 20th Century"

[[entries.books]]
author = "Eric Schmidt; Jonathan Rosenberg"
date_finished = "7 Apr"
isbn = "9781444792485"
title = "How Google Works"
