base_url = "https://www.rafael.me.uk"
compile_sass = true
description = "Personal website of Rafael Alves Sa"
ignored_content = ["*.toml"]
output_dir = "../docs"
title = "Rafael Alves Sa"

[markdown]
external_links_no_follow = true
external_links_no_referrer = true
external_links_target_blank = true
smart_punctuation = true

[extra]
author = "Rafael Alves Sa"
email = "rafael@rafael.me.uk"
github = "https://github.com/rafaelalvessa"
pgp = "AE8232A02B2F4F7B5316538662B3ABFD3DD4A9C4"
